In [1]:
import pandas as pd
import numpy as np

### UCSF_FSX7 Dataset

In [2]:
ucsf = pd.read_csv('/Users/hieubui/Documents/Thesis 2027/data/ucsf_fsx7.csv')
ucsf.head()

/var/folders/2g/pgg7x75x41l26xt78n1j5hk00000gn/T/ipykernel_81702/2498482110.py:1: DtypeWarning: Columns (11,12,13,14,15,16,17,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  ucsf = pd.read_csv('/Users/hieubui/Documents/Thesis 2027/data/ucsf_fsx7.csv')

,PHASE,PTID,RID,VISCODE,VISCODE2,IMAGEUID,FIELD_STRENGTH,EXAMDATE,RUNDATE,STATUS,...,ST147SV,ST148SV,ST149SV,ST150SV,ST151SV,ST152SV,ST153SV,ST154SV,ST155SV,update_stamp
0,ADNI3,002_S_4213,4213,init,m72,888008,3T,2017-08-14,2022-07-23,partial,...,217434.885092,217173.802571,434608.687663,175240.0,171111.0,346351.0,47936.0,576920.687663,874725.0,2024-12-02 08:27:54
1,ADNI2,116_S_4453,4453,v02,scmri,281425,3T,2012-01-18,2022-10-05,partial,...,224522.552452,221805.186019,446327.738471,225291.0,221178.0,446469.0,50711.0,599707.738471,984072.0,2024-12-02 08:27:54
2,ADNI2,099_S_4104,4104,v11,m12,322667,3T,2012-07-11,2022-09-26,partial,...,219930.656696,224579.475317,444510.132013,199702.0,200555.0,400257.0,52008.0,596412.132013,928837.0,2024-12-02 08:27:54
3,ADNI2,073_S_2153,2153,v21,m36,417092,3T,2014-03-03,2022-08-14,partial,...,200725.779310,201273.901030,401999.680340,174186.0,176432.0,350618.0,49603.0,538118.680340,846706.0,2024-12-02 08:27:54
4,ADNI2,137_S_4303,4303,v04,m03,288921,3T,2012-02-27,2022-10-05,partial,...,198949.362921,200313.596282,399262.959202,202949.5,196986.5,399936.0,47355.0,543084.959202,902306.0,2024-12-02 08:27:54

In [3]:
# Show information of all columns except 'ST*' columns
ucsf_info = ucsf.drop(columns=[col for col in ucsf.columns if col.startswith('ST')]).info()
print(ucsf_info)
print(ucsf.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12290 entries, 0 to 12289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PHASE           12290 non-null  object
 1   PTID            12290 non-null  object
 2   RID             12290 non-null  int64
 3   VISCODE         12290 non-null  object
 4   VISCODE2        12286 non-null  object
 5   IMAGEUID        12290 non-null  int64
 6   FIELD_STRENGTH  12290 non-null  object
 7   EXAMDATE        12290 non-null  object
 8   RUNDATE         12290 non-null  object
 9   FSVER           12290 non-null  object
 10  OVERALLQC       1155 non-null   object
 11  TEMPQC          1155 non-null   object
 12  FRONTQC         1155 non-null   object
 13  PARQC           1155 non-null   object
 14  INSULAQC        1155 non-null   object
 15  OCCQC           1155 non-null   object
 16  BGQC            1155 non-null   object
 17  CWMQC           1155 non-null   object
 18  VENTQC          1155 non-null   object
 19  HIPPOQC         1155 non-null   object
 20  update_stamp    12290 non-null  object
dtypes: int64(2), object(19)
memory usage: 2.0+ MB
None
(12290, 347)

In [4]:
# Drop unnecessary columns
ucsf1 = ucsf.drop(columns=['RID', 'VISCODE', 'IMAGEUID', 'EXAMDATE', 'RUNDATE',
                           'FSVER', 'OVERALLQC', 'TEMPQC', 'FRONTQC', 'PARQC',
                           'INSULAQC', 'OCCQC', 'BGQC', 'CWMQC', 'VENTQC', 'HIPPOQC', 'update_stamp', 'STATUS'])

In [5]:
# Select only 3T values in FIELD_STRENGTH column
ucsf1 = ucsf1[ucsf1['FIELD_STRENGTH'] == '3T']

# Drop FIELD_STRENGTH column
ucsf1 = ucsf1.drop(columns=['FIELD_STRENGTH'])
ucsf1.head()

,PHASE,PTID,VISCODE2,ST101SV,ST102CV,ST102SA,ST102TA,ST102TS,ST103CV,ST103SA,...,ST9SV,ST147SV,ST148SV,ST149SV,ST150SV,ST151SV,ST152SV,ST153SV,ST154SV,ST155SV
0,ADNI3,002_S_4213,m72,1362.0,3775.0,1141.0,2.600,0.737,2495.0,661.0,...,1866.4,217434.885092,217173.802571,434608.687663,175240.0,171111.0,346351.0,47936.0,576920.687663,874725.0
1,ADNI2,116_S_4453,scmri,1532.0,3174.0,1472.0,2.051,0.517,1626.0,573.0,...,1707.8,224522.552452,221805.186019,446327.738471,225291.0,221178.0,446469.0,50711.0,599707.738471,984072.0
2,ADNI2,099_S_4104,m12,1796.4,3555.0,1258.0,2.646,0.732,1743.0,535.0,...,3493.8,219930.656696,224579.475317,444510.132013,199702.0,200555.0,400257.0,52008.0,596412.132013,928837.0
3,ADNI2,073_S_2153,m36,1583.0,3460.0,1318.0,2.377,0.601,2087.0,643.0,...,2618.2,200725.779310,201273.901030,401999.680340,174186.0,176432.0,350618.0,49603.0,538118.680340,846706.0
4,ADNI2,137_S_4303,m03,1916.1,2979.0,1161.0,2.421,0.583,1441.0,503.0,...,1528.3,198949.362921,200313.596282,399262.959202,202949.5,196986.5,399936.0,47355.0,543084.959202,902306.0

In [6]:
# Sum missing values in each column
missing_values = ucsf1.isnull().sum()
print(missing_values.sort_values(ascending=False))

ST8SV       7724
ST68SV      7241
ST82TS       362
ST97SA       362
ST97CV       362
            ...
ST46SA        17
ST10CV         7
VISCODE2       4
PTID           0
PHASE          0
Length: 328, dtype: int64

In [7]:
# Drop features with most  missing values
ucsf1.drop(columns=['ST8SV', 'ST68SV'])

,PHASE,PTID,VISCODE2,ST101SV,ST102CV,ST102SA,ST102TA,ST102TS,ST103CV,ST103SA,...,ST9SV,ST147SV,ST148SV,ST149SV,ST150SV,ST151SV,ST152SV,ST153SV,ST154SV,ST155SV
0,ADNI3,002_S_4213,m72,1362.0,3775.0,1141.0,2.600,0.737,2495.0,661.0,...,1866.4,217434.885092,217173.802571,434608.687663,175240.0,171111.0,346351.0,47936.0,576920.687663,874725.0
1,ADNI2,116_S_4453,scmri,1532.0,3174.0,1472.0,2.051,0.517,1626.0,573.0,...,1707.8,224522.552452,221805.186019,446327.738471,225291.0,221178.0,446469.0,50711.0,599707.738471,984072.0
2,ADNI2,099_S_4104,m12,1796.4,3555.0,1258.0,2.646,0.732,1743.0,535.0,...,3493.8,219930.656696,224579.475317,444510.132013,199702.0,200555.0,400257.0,52008.0,596412.132013,928837.0
3,ADNI2,073_S_2153,m36,1583.0,3460.0,1318.0,2.377,0.601,2087.0,643.0,...,2618.2,200725.779310,201273.901030,401999.680340,174186.0,176432.0,350618.0,49603.0,538118.680340,846706.0
4,ADNI2,137_S_4303,m03,1916.1,2979.0,1161.0,2.421,0.583,1441.0,503.0,...,1528.3,198949.362921,200313.596282,399262.959202,202949.5,196986.5,399936.0,47355.0,543084.959202,902306.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12285,ADNI4,027_S_10751,sc,1919.7,3699.0,1480.0,2.300,0.674,1957.0,577.0,...,1456.4,194418.668798,194344.227625,388762.896423,199821.5,197427.5,397249.0,53465.0,554341.896423,868775.0
12286,ADNI4,035_S_4785,m150,1665.7,3647.0,1465.0,2.325,0.445,2005.0,610.0,...,1857.2,201474.147739,205217.039059,406691.186798,186948.0,186500.0,373448.0,46924.0,558994.186798,872957.0
12287,ADNI4,305_S_10282,sc,1867.6,2631.0,1088.0,2.338,0.504,1809.0,670.0,...,3037.9,167323.021126,162171.660183,329494.681309,160833.0,157610.0,318443.0,46213.0,475310.681309,769650.0
12288,ADNI4,127_S_6436,m84,1733.9,3162.0,1406.0,2.173,0.464,1835.0,608.0,...,3073.0,207223.996907,212155.328084,419379.324991,201180.0,202781.0,403961.0,52549.0,567032.324991,933962.0
12289,ADNI4,168_S_6371,m90,1805.6,3576.0,1485.0,2.335,0.521,1800.0,592.0,...,2719.0,205796.119039,205006.203113,410802.322152,215515.5,215889.5,431405.0,50577.0,566327.322152,949370.0

### adni_all Dataset

In [8]:
all = pd.read_csv("/Users/hieubui/Documents/Thesis 2027/data/adni_all.csv")
all.head()

,subject_id,visit,PTGENDER,entry_age,entry_research_group,PTRACCAT,PTETHCAT,PTEDUCAT,GENOTYPE,CDRSB,...,LIMMTOTAL,VSWEIGHT,VSHEIGHT,VSBPSYS,VSBPDIA,GDTOTAL,CATANIMSC,FAQTOTAL,NPISCORE,TOTAL13
0,002_S_0295,bl,1.0,84.84,CN,NaN,NaN,NaN,3/4,NaN,...,NaN,75.0,NaN,148.0,66.0,NaN,13.0,0.0,0.0,4.00
1,002_S_0295,m06,1.0,84.84,CN,NaN,NaN,NaN,3/4,0.0,...,NaN,74.1,NaN,135.0,66.0,NaN,19.0,0.0,0.0,6.33
2,002_S_0295,m12,1.0,84.84,CN,NaN,NaN,NaN,3/4,0.0,...,18.0,72.6,NaN,126.0,58.0,0.0,22.0,0.0,0.0,5.67
3,002_S_0295,m18,1.0,84.84,CN,NaN,NaN,NaN,3/4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,002_S_0295,m24,1.0,84.84,CN,NaN,NaN,NaN,3/4,0.0,...,12.0,162.6,NaN,136.0,62.0,0.0,16.0,0.0,0.0,5.67

In [9]:
# Drop unnecessary columns
all1 = all.drop(columns=['PTRACCAT', 'PTETHCAT', 'PTEDUCAT', 'AVDEL30MIN', 'AVDELTOT', 'LIMMTOTAL',
                             'VSWEIGHT', 'VSHEIGHT','VSBPSYS', 'VSBPDIA','NPISCORE', 'GENOTYPE'])
all1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24132 entries, 0 to 24131
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   subject_id            24132 non-null  object
 1   visit                 24132 non-null  object
 2   PTGENDER              24082 non-null  float64
 3   entry_age             24080 non-null  float64
 4   entry_research_group  23253 non-null  object
 5   CDRSB                 14156 non-null  float64
 6   TRAASCOR              12510 non-null  float64
 7   TRABSCOR              12154 non-null  float64
 8   LDELTOTAL             12101 non-null  float64
 9   MMSCORE               14056 non-null  float64
 10  GDTOTAL               13149 non-null  float64
 11  CATANIMSC             12611 non-null  float64
 12  FAQTOTAL              12983 non-null  float64
 13  TOTAL13               12492 non-null  float64
dtypes: float64(11), object(3)
memory usage: 2.6+ MB

### Join ucsf1 and all dataset

In [10]:
# Join the ucsf1 and all1 dataframes with 
# Matching ucsf1['PTID'] and all1[subject ID] and
# Matching ucsf1['VISCODE2'] and all1['visit']

merged_df = pd.merge(all1, ucsf1, left_on=['subject_id', 'visit'], right_on=['PTID', 'VISCODE2'], how='left')
merged_df.head()

,subject_id,visit,PTGENDER,entry_age,entry_research_group,CDRSB,TRAASCOR,TRABSCOR,LDELTOTAL,MMSCORE,...,ST9SV,ST147SV,ST148SV,ST149SV,ST150SV,ST151SV,ST152SV,ST153SV,ST154SV,ST155SV
0,002_S_0295,bl,1.0,84.84,CN,NaN,45.0,300.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,002_S_0295,m06,1.0,84.84,CN,0.0,23.0,68.0,NaN,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,002_S_0295,m12,1.0,84.84,CN,0.0,30.0,72.0,15.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,002_S_0295,m18,1.0,84.84,CN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,002_S_0295,m24,1.0,84.84,CN,0.0,38.0,120.0,10.0,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
merged_info = merged_df.drop(columns=[col for col in merged_df.columns if col.startswith('ST')]).info()
print(merged_info)
print(merged_df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24198 entries, 0 to 24197
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   subject_id            24198 non-null  object
 1   visit                 24198 non-null  object
 2   PTGENDER              24148 non-null  float64
 3   entry_age             24146 non-null  float64
 4   entry_research_group  23319 non-null  object
 5   CDRSB                 14220 non-null  float64
 6   TRAASCOR              12534 non-null  float64
 7   TRABSCOR              12177 non-null  float64
 8   LDELTOTAL             12163 non-null  float64
 9   MMSCORE               14120 non-null  float64
 10  GDTOTAL               13211 non-null  float64
 11  CATANIMSC             12635 non-null  float64
 12  FAQTOTAL              13008 non-null  float64
 13  TOTAL13               12515 non-null  float64
 14  PHASE                 7555 non-null   object
 15  PTID                  7555 non-null   object
 16  VISCODE2              7555 non-null   object
dtypes: float64(11), object(6)
memory usage: 3.1+ MB
None
(24198, 342)

In [12]:
merged_df = merged_df.drop(columns=['PTID', 'VISCODE2'])

### All_fMRI

In [14]:
fmri = pd.read_csv("/Users/hieubui/Documents/Thesis 2027/data/all_fmri.csv")
fmri.head()

,image_id,subject_id,study_id,fmri_visit,fmri_date,fmri_description,fmri_mfr,fmri_mfr_model,fmri_field_str,fmri_sequence,fmri_te,fmri_tr,fmri_flip_angle,fmri_width,fmri_height,fmri_n_images,fmri_pixel_x,fmri_pixel_y,fmri_thickness
0,901029,127_S_1427,115027,m120,2017-09-06,Cerebral Blood Flow,GE MEDICAL SYSTEMS,DISCOVERY MR750,3.0,RM,10.53,4886.0,111,128.0,128.0,40,1.8750,1.8750,4.0
1,901030,127_S_1427,115027,m120,2017-09-06,Axial 3D pCASL (Eyes Open),GE MEDICAL SYSTEMS,DISCOVERY MR750,3.0,RM,10.53,4886.0,111,128.0,128.0,80,1.8750,1.8750,4.0
2,901033,127_S_1427,115027,m120,2017-09-06,Axial rsfMRI (Eyes Open),GE MEDICAL SYSTEMS,DISCOVERY MR750,3.0,EP/GR,30.00,3000.0,90,64.0,64.0,9600,3.4375,3.4375,3.4
3,1059957,127_S_1427,127633,m132,2018-10-12,Axial 3D pCASL (Eyes Open),GE MEDICAL SYSTEMS,DISCOVERY MR750,3.0,RM,11.11,4917.0,111,128.0,128.0,80,1.8750,1.8750,4.0
4,1059961,127_S_1427,127633,m132,2018-10-12,Axial rsfMRI (Eyes Open),GE MEDICAL SYSTEMS,DISCOVERY MR750,3.0,EP/GR,30.00,3000.0,90,64.0,64.0,9600,3.4375,3.4375,3.4

In [15]:
# Select 3.0 in the fmri_field_str column
fmri = fmri[fmri['fmri_field_str'] == 3.0]

# Drop unnecessary columns
fmri1 = fmri.drop(columns=['image_id', 'study_id', 'fmri_date', 'fmri_mfr', 'fmri_mfr_model', 'fmri_field_str', 'fmri_sequence', 'fmri_flip_angle', 
                           'fmri_width', 'fmri_height', 'fmri_n_images', 'fmri_pixel_x', 'fmri_pixel_y', 'fmri_thickness', 'fmri_te'])

In [16]:
print(fmri1.info())
print(fmri1.shape)

<class 'pandas.core.frame.DataFrame'>
Index: 19153 entries, 0 to 19154
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   subject_id        19153 non-null  object
 1   fmri_visit        19153 non-null  object
 2   fmri_description  19153 non-null  object
 3   fmri_tr           19153 non-null  float64
dtypes: float64(1), object(3)
memory usage: 748.2+ KB
None
(19153, 4)

In [17]:
# Count values in fmri_visit column
fmri1['fmri_visit'].value_counts()

fmri_visit
sc       4268
m12      2214
m24      1842
scmri    1673
m03      1358
m06      1231
m48      1118
m72       642
m36       456
m84       445
m96       435
m78       430
m90       311
m66       302
m60       280
m54       205
m30       193
m132      166
m120      154
m102      152
m108      137
m156      136
m138      124
m42       120
m150      114
m144      108
m114       83
m168       79
m126       76
m162       63
m18        54
m180       41
m174       36
t_bl       33
m186       15
m216       13
m210       12
m234        8
m228        7
m240        6
UNK         6
m192        3
m222        3
m204        1
Name: count, dtype: int64

In [22]:
# Only keep rows having 'rsfmri' or 'Resting State fMRI' in fmri_description column
fmri1 = fmri1[fmri1['fmri_description'].isin(['rsfmri', 'Resting State fMRI'])]

In [23]:
fmri1.head()

     subject_id fmri_visit    fmri_description  fmri_tr
200  136_S_0107        m72  Resting State fMRI   3000.0
202  136_S_0186        m72  Resting State fMRI   3000.0
249  002_S_0295        m60  Resting State fMRI   3000.0
250  002_S_0295        m72  Resting State fMRI   3001.0
251  002_S_0413        m60  Resting State fMRI   3000.0

### Join fmri1 + merged_df

In [24]:
# Join fmri1 with merged_df
# Matching both subject_id
# Matching fmri1['fmri_visit'] and merged_df['visit']
# Insert the fmri1 columns before merged_df['ST*'] columns
merged_fmri = pd.merge(merged_df, fmri1, left_on=['subject_id', 'visit'], right_on=['subject_id', 'fmri_visit'], how='left')

In [25]:
fmri_cols = ['fmri_visit', 'fmri_description', 'fmri_tr']

# Find first ST column
st_pos = next(i for i, c in enumerate(merged_fmri.columns) if c.startswith('ST'))

# Move the 3 fMRI columns right before ST*
for col in reversed(fmri_cols):
    merged_fmri.insert(st_pos, col, merged_fmri.pop(col))

In [26]:
merged_fmri.head()

,subject_id,visit,PTGENDER,entry_age,entry_research_group,CDRSB,TRAASCOR,TRABSCOR,LDELTOTAL,MMSCORE,...,ST9SV,ST147SV,ST148SV,ST149SV,ST150SV,ST151SV,ST152SV,ST153SV,ST154SV,ST155SV
0,002_S_0295,bl,1.0,84.84,CN,NaN,45.0,300.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,002_S_0295,m06,1.0,84.84,CN,0.0,23.0,68.0,NaN,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,002_S_0295,m12,1.0,84.84,CN,0.0,30.0,72.0,15.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,002_S_0295,m18,1.0,84.84,CN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,002_S_0295,m24,1.0,84.84,CN,0.0,38.0,120.0,10.0,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# Save the merged dataframe to a CSV file
merged_fmri.to_csv("/Users/hieubui/Documents/Thesis 2027/data/merged_fmri.csv", index=False)